updated WALinux agent to 2.9.0.4
dmauser/opnazure pull request #51
Opened 2023-09-01 05:42 UTC by cjnova

tested WALinux agent 2.9.0. update

2023-09-01 05:43 UTC, cjnova commented
tested WALinux agent 2.9.0.4 update

2023-11-18 04:13 UTC, dmauser commented on bicep/main.bicep
> +// Change password to one knew to be able to login in FreeBSD without root user
This change breaks the deployment. It forces we use the Windows password.

2023-11-18 04:16 UTC, dmauser requested changes
@cjnova  Can you fix and resubmit based on the comments below? In short, we need to leave var TempPassword to generate random during the installation.

2023-11-18 04:16 UTC, dmauser commented on bicep/main.bicep
> +var TempPassword = WinPassword
We need to leave the password generated randomly.

2023-11-18 04:16 UTC, dmauser commented on bicep/main.bicep
> +var TempPassword = WinPassword
BTW, thanks for your suggestions to improve this project.

2023-11-18 04:18 UTC, dmauser commented on bicep/main.bicep
> +var TempPassword = WinPassword
CCing @Welasco as FYI

2023-11-20 00:41 UTC, Welasco commented
Just a heads up for both of you @dmauser  and @cjnova. I'm working on it.

Tks a lot for all the changes @cjnova, I'll test it all.

2023-11-21 01:32 UTC, dmauser commented
Closing the pull request per Victor's update.

2023-11-21 01:32 UTC, closed without merging